// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANSJjJ3Jk13RrWrbJhOhVYukMwG9Mx0Xg',
    appId: '1:939732836583:android:eeb4dfe669136d3d0c8242',
    messagingSenderId: '939732836583',
    projectId: 'conningtower-1',
    storageBucket: 'conningtower-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhxbhRG7vb-dOeupfOFa31cLSyecXZ-o',
    appId: '1:939732836583:ios:023bff836d1765f50c8242',
    messagingSenderId: '939732836583',
    projectId: 'conningtower-1',
    storageBucket: 'conningtower-1.appspot.com',
    iosBundleId: 'com.conntower.open',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhxbhRG7vb-dOeupfOFa31cLSyecXZ-o',
    appId: '1:939732836583:ios:caa20e1f07b7f34c0c8242',
    messagingSenderId: '939732836583',
    projectId: 'conningtower-1',
    storageBucket: 'conningtower-1.appspot.com',
    iosClientId: '939732836583-98ufephpr85cf8e3g8hn7kluq9j5p543.apps.googleusercontent.com',
    iosBundleId: 'com.conntower.conningTower',
  );
}
